services:
  - type: web
    name: E2A
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_KEY
        sync: false
      - key: TEMP_DIR
        value: /tmp/audio_jobs
      - key: AUDIO_CLIP_SECONDS
        value: "30"
      - key: COOKIES_BASE64
        sync: false
      - key: PROXY
        sync: false
